/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.raybia.dealer.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.raybia.dealer.model.Dealer;
import com.liferay.raybia.dealer.model.DealerModel;
import com.liferay.raybia.dealer.model.DealerSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.math.BigDecimal;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Dealer service. Represents a row in the &quot;Raybia_Dealer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DealerModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DealerImpl}.
 * </p>
 *
 * @author Peter Richards
 * @see DealerImpl
 * @generated
 */
@JSON(strict = true)
public class DealerModelImpl
	extends BaseModelImpl<Dealer> implements DealerModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dealer model instance should use the <code>Dealer</code> interface instead.
	 */
	public static final String TABLE_NAME = "Raybia_Dealer";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"dealerId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"street", Types.VARCHAR},
		{"locality", Types.VARCHAR}, {"state_", Types.VARCHAR},
		{"postalCode", Types.VARCHAR}, {"emailAddress", Types.VARCHAR},
		{"phoneNumber", Types.VARCHAR}, {"openingHours", Types.VARCHAR},
		{"latitude", Types.DECIMAL}, {"longitude", Types.DECIMAL},
		{"displayDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dealerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("street", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("locality", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("state_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postalCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("emailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phoneNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("openingHours", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("latitude", Types.DECIMAL);
		TABLE_COLUMNS_MAP.put("longitude", Types.DECIMAL);
		TABLE_COLUMNS_MAP.put("displayDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Raybia_Dealer (uuid_ VARCHAR(75) null,dealerId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name STRING null,street STRING null,locality STRING null,state_ STRING null,postalCode VARCHAR(75) null,emailAddress VARCHAR(75) null,phoneNumber VARCHAR(75) null,openingHours STRING null,latitude DECIMAL(30, 16) null,longitude DECIMAL(30, 16) null,displayDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Raybia_Dealer";

	public static final String ORDER_BY_JPQL = " ORDER BY dealer.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Raybia_Dealer.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DISPLAYDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Dealer toModel(DealerSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Dealer model = new DealerImpl();

		model.setUuid(soapModel.getUuid());
		model.setDealerId(soapModel.getDealerId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setStreet(soapModel.getStreet());
		model.setLocality(soapModel.getLocality());
		model.setState(soapModel.getState());
		model.setPostalCode(soapModel.getPostalCode());
		model.setEmailAddress(soapModel.getEmailAddress());
		model.setPhoneNumber(soapModel.getPhoneNumber());
		model.setOpeningHours(soapModel.getOpeningHours());
		model.setLatitude(soapModel.getLatitude());
		model.setLongitude(soapModel.getLongitude());
		model.setDisplayDate(soapModel.getDisplayDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Dealer> toModels(DealerSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Dealer> models = new ArrayList<Dealer>(soapModels.length);

		for (DealerSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public DealerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dealerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDealerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dealerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Dealer.class;
	}

	@Override
	public String getModelClassName() {
		return Dealer.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Dealer, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Dealer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Dealer, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Dealer)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Dealer, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Dealer, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Dealer)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Dealer, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Dealer, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Dealer>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Dealer.class.getClassLoader(), Dealer.class, ModelWrapper.class);

		try {
			Constructor<Dealer> constructor =
				(Constructor<Dealer>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Dealer, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Dealer, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Dealer, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Dealer, Object>>();
		Map<String, BiConsumer<Dealer, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Dealer, ?>>();

		attributeGetterFunctions.put("uuid", Dealer::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Dealer, String>)Dealer::setUuid);
		attributeGetterFunctions.put("dealerId", Dealer::getDealerId);
		attributeSetterBiConsumers.put(
			"dealerId", (BiConsumer<Dealer, Long>)Dealer::setDealerId);
		attributeGetterFunctions.put("groupId", Dealer::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Dealer, Long>)Dealer::setGroupId);
		attributeGetterFunctions.put("companyId", Dealer::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Dealer, Long>)Dealer::setCompanyId);
		attributeGetterFunctions.put("userId", Dealer::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Dealer, Long>)Dealer::setUserId);
		attributeGetterFunctions.put("userName", Dealer::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Dealer, String>)Dealer::setUserName);
		attributeGetterFunctions.put("createDate", Dealer::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Dealer, Date>)Dealer::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Dealer::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Dealer, Date>)Dealer::setModifiedDate);
		attributeGetterFunctions.put("name", Dealer::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Dealer, String>)Dealer::setName);
		attributeGetterFunctions.put("street", Dealer::getStreet);
		attributeSetterBiConsumers.put(
			"street", (BiConsumer<Dealer, String>)Dealer::setStreet);
		attributeGetterFunctions.put("locality", Dealer::getLocality);
		attributeSetterBiConsumers.put(
			"locality", (BiConsumer<Dealer, String>)Dealer::setLocality);
		attributeGetterFunctions.put("state", Dealer::getState);
		attributeSetterBiConsumers.put(
			"state", (BiConsumer<Dealer, String>)Dealer::setState);
		attributeGetterFunctions.put("postalCode", Dealer::getPostalCode);
		attributeSetterBiConsumers.put(
			"postalCode", (BiConsumer<Dealer, String>)Dealer::setPostalCode);
		attributeGetterFunctions.put("emailAddress", Dealer::getEmailAddress);
		attributeSetterBiConsumers.put(
			"emailAddress",
			(BiConsumer<Dealer, String>)Dealer::setEmailAddress);
		attributeGetterFunctions.put("phoneNumber", Dealer::getPhoneNumber);
		attributeSetterBiConsumers.put(
			"phoneNumber", (BiConsumer<Dealer, String>)Dealer::setPhoneNumber);
		attributeGetterFunctions.put("openingHours", Dealer::getOpeningHours);
		attributeSetterBiConsumers.put(
			"openingHours",
			(BiConsumer<Dealer, String>)Dealer::setOpeningHours);
		attributeGetterFunctions.put("latitude", Dealer::getLatitude);
		attributeSetterBiConsumers.put(
			"latitude", (BiConsumer<Dealer, BigDecimal>)Dealer::setLatitude);
		attributeGetterFunctions.put("longitude", Dealer::getLongitude);
		attributeSetterBiConsumers.put(
			"longitude", (BiConsumer<Dealer, BigDecimal>)Dealer::setLongitude);
		attributeGetterFunctions.put("displayDate", Dealer::getDisplayDate);
		attributeSetterBiConsumers.put(
			"displayDate", (BiConsumer<Dealer, Date>)Dealer::setDisplayDate);
		attributeGetterFunctions.put("status", Dealer::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Dealer, Integer>)Dealer::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Dealer::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Dealer, Long>)Dealer::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Dealer::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Dealer, String>)Dealer::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Dealer::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<Dealer, Date>)Dealer::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getDealerId() {
		return _dealerId;
	}

	@Override
	public void setDealerId(long dealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dealerId = dealerId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getName(), languageId, useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(
				LocalizationUtil.updateLocalization(
					getName(), "Name", name, languageId, defaultLanguageId));
		}
		else {
			setName(
				LocalizationUtil.removeLocalization(
					getName(), "Name", languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(
			LocalizationUtil.updateLocalization(
				nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getStreet() {
		if (_street == null) {
			return "";
		}
		else {
			return _street;
		}
	}

	@Override
	public String getStreet(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getStreet(languageId);
	}

	@Override
	public String getStreet(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getStreet(languageId, useDefault);
	}

	@Override
	public String getStreet(String languageId) {
		return LocalizationUtil.getLocalization(getStreet(), languageId);
	}

	@Override
	public String getStreet(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getStreet(), languageId, useDefault);
	}

	@Override
	public String getStreetCurrentLanguageId() {
		return _streetCurrentLanguageId;
	}

	@JSON
	@Override
	public String getStreetCurrentValue() {
		Locale locale = getLocale(_streetCurrentLanguageId);

		return getStreet(locale);
	}

	@Override
	public Map<Locale, String> getStreetMap() {
		return LocalizationUtil.getLocalizationMap(getStreet());
	}

	@Override
	public void setStreet(String street) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_street = street;
	}

	@Override
	public void setStreet(String street, Locale locale) {
		setStreet(street, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setStreet(String street, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(street)) {
			setStreet(
				LocalizationUtil.updateLocalization(
					getStreet(), "Street", street, languageId,
					defaultLanguageId));
		}
		else {
			setStreet(
				LocalizationUtil.removeLocalization(
					getStreet(), "Street", languageId));
		}
	}

	@Override
	public void setStreetCurrentLanguageId(String languageId) {
		_streetCurrentLanguageId = languageId;
	}

	@Override
	public void setStreetMap(Map<Locale, String> streetMap) {
		setStreetMap(streetMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setStreetMap(
		Map<Locale, String> streetMap, Locale defaultLocale) {

		if (streetMap == null) {
			return;
		}

		setStreet(
			LocalizationUtil.updateLocalization(
				streetMap, getStreet(), "Street",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getLocality() {
		if (_locality == null) {
			return "";
		}
		else {
			return _locality;
		}
	}

	@Override
	public String getLocality(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLocality(languageId);
	}

	@Override
	public String getLocality(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLocality(languageId, useDefault);
	}

	@Override
	public String getLocality(String languageId) {
		return LocalizationUtil.getLocalization(getLocality(), languageId);
	}

	@Override
	public String getLocality(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getLocality(), languageId, useDefault);
	}

	@Override
	public String getLocalityCurrentLanguageId() {
		return _localityCurrentLanguageId;
	}

	@JSON
	@Override
	public String getLocalityCurrentValue() {
		Locale locale = getLocale(_localityCurrentLanguageId);

		return getLocality(locale);
	}

	@Override
	public Map<Locale, String> getLocalityMap() {
		return LocalizationUtil.getLocalizationMap(getLocality());
	}

	@Override
	public void setLocality(String locality) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_locality = locality;
	}

	@Override
	public void setLocality(String locality, Locale locale) {
		setLocality(locality, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setLocality(
		String locality, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(locality)) {
			setLocality(
				LocalizationUtil.updateLocalization(
					getLocality(), "Locality", locality, languageId,
					defaultLanguageId));
		}
		else {
			setLocality(
				LocalizationUtil.removeLocalization(
					getLocality(), "Locality", languageId));
		}
	}

	@Override
	public void setLocalityCurrentLanguageId(String languageId) {
		_localityCurrentLanguageId = languageId;
	}

	@Override
	public void setLocalityMap(Map<Locale, String> localityMap) {
		setLocalityMap(localityMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setLocalityMap(
		Map<Locale, String> localityMap, Locale defaultLocale) {

		if (localityMap == null) {
			return;
		}

		setLocality(
			LocalizationUtil.updateLocalization(
				localityMap, getLocality(), "Locality",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getState() {
		if (_state == null) {
			return "";
		}
		else {
			return _state;
		}
	}

	@Override
	public String getState(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getState(languageId);
	}

	@Override
	public String getState(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getState(languageId, useDefault);
	}

	@Override
	public String getState(String languageId) {
		return LocalizationUtil.getLocalization(getState(), languageId);
	}

	@Override
	public String getState(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getState(), languageId, useDefault);
	}

	@Override
	public String getStateCurrentLanguageId() {
		return _stateCurrentLanguageId;
	}

	@JSON
	@Override
	public String getStateCurrentValue() {
		Locale locale = getLocale(_stateCurrentLanguageId);

		return getState(locale);
	}

	@Override
	public Map<Locale, String> getStateMap() {
		return LocalizationUtil.getLocalizationMap(getState());
	}

	@Override
	public void setState(String state) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_state = state;
	}

	@Override
	public void setState(String state, Locale locale) {
		setState(state, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setState(String state, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(state)) {
			setState(
				LocalizationUtil.updateLocalization(
					getState(), "State", state, languageId, defaultLanguageId));
		}
		else {
			setState(
				LocalizationUtil.removeLocalization(
					getState(), "State", languageId));
		}
	}

	@Override
	public void setStateCurrentLanguageId(String languageId) {
		_stateCurrentLanguageId = languageId;
	}

	@Override
	public void setStateMap(Map<Locale, String> stateMap) {
		setStateMap(stateMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setStateMap(
		Map<Locale, String> stateMap, Locale defaultLocale) {

		if (stateMap == null) {
			return;
		}

		setState(
			LocalizationUtil.updateLocalization(
				stateMap, getState(), "State",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getPostalCode() {
		if (_postalCode == null) {
			return "";
		}
		else {
			return _postalCode;
		}
	}

	@Override
	public void setPostalCode(String postalCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_postalCode = postalCode;
	}

	@JSON
	@Override
	public String getEmailAddress() {
		if (_emailAddress == null) {
			return "";
		}
		else {
			return _emailAddress;
		}
	}

	@Override
	public void setEmailAddress(String emailAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_emailAddress = emailAddress;
	}

	@JSON
	@Override
	public String getPhoneNumber() {
		if (_phoneNumber == null) {
			return "";
		}
		else {
			return _phoneNumber;
		}
	}

	@Override
	public void setPhoneNumber(String phoneNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phoneNumber = phoneNumber;
	}

	@JSON
	@Override
	public String getOpeningHours() {
		if (_openingHours == null) {
			return "";
		}
		else {
			return _openingHours;
		}
	}

	@Override
	public String getOpeningHours(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getOpeningHours(languageId);
	}

	@Override
	public String getOpeningHours(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getOpeningHours(languageId, useDefault);
	}

	@Override
	public String getOpeningHours(String languageId) {
		return LocalizationUtil.getLocalization(getOpeningHours(), languageId);
	}

	@Override
	public String getOpeningHours(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getOpeningHours(), languageId, useDefault);
	}

	@Override
	public String getOpeningHoursCurrentLanguageId() {
		return _openingHoursCurrentLanguageId;
	}

	@JSON
	@Override
	public String getOpeningHoursCurrentValue() {
		Locale locale = getLocale(_openingHoursCurrentLanguageId);

		return getOpeningHours(locale);
	}

	@Override
	public Map<Locale, String> getOpeningHoursMap() {
		return LocalizationUtil.getLocalizationMap(getOpeningHours());
	}

	@Override
	public void setOpeningHours(String openingHours) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_openingHours = openingHours;
	}

	@Override
	public void setOpeningHours(String openingHours, Locale locale) {
		setOpeningHours(openingHours, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setOpeningHours(
		String openingHours, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(openingHours)) {
			setOpeningHours(
				LocalizationUtil.updateLocalization(
					getOpeningHours(), "OpeningHours", openingHours, languageId,
					defaultLanguageId));
		}
		else {
			setOpeningHours(
				LocalizationUtil.removeLocalization(
					getOpeningHours(), "OpeningHours", languageId));
		}
	}

	@Override
	public void setOpeningHoursCurrentLanguageId(String languageId) {
		_openingHoursCurrentLanguageId = languageId;
	}

	@Override
	public void setOpeningHoursMap(Map<Locale, String> openingHoursMap) {
		setOpeningHoursMap(openingHoursMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setOpeningHoursMap(
		Map<Locale, String> openingHoursMap, Locale defaultLocale) {

		if (openingHoursMap == null) {
			return;
		}

		setOpeningHours(
			LocalizationUtil.updateLocalization(
				openingHoursMap, getOpeningHours(), "OpeningHours",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public BigDecimal getLatitude() {
		return _latitude;
	}

	@Override
	public void setLatitude(BigDecimal latitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_latitude = latitude;
	}

	@JSON
	@Override
	public BigDecimal getLongitude() {
		return _longitude;
	}

	@Override
	public void setLongitude(BigDecimal longitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_longitude = longitude;
	}

	@JSON
	@Override
	public Date getDisplayDate() {
		return _displayDate;
	}

	@Override
	public void setDisplayDate(Date displayDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_displayDate = displayDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalDisplayDate() {
		return getColumnOriginalValue("displayDate");
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Dealer.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Dealer.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> streetMap = getStreetMap();

		for (Map.Entry<Locale, String> entry : streetMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> localityMap = getLocalityMap();

		for (Map.Entry<Locale, String> entry : localityMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> stateMap = getStateMap();

		for (Map.Entry<Locale, String> entry : stateMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> openingHoursMap = getOpeningHoursMap();

		for (Map.Entry<Locale, String> entry : openingHoursMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			Dealer.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}

		String street = getStreet(defaultLocale);

		if (Validator.isNull(street)) {
			setStreet(getStreet(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setStreet(getStreet(defaultLocale), defaultLocale, defaultLocale);
		}

		String locality = getLocality(defaultLocale);

		if (Validator.isNull(locality)) {
			setLocality(getLocality(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setLocality(
				getLocality(defaultLocale), defaultLocale, defaultLocale);
		}

		String state = getState(defaultLocale);

		if (Validator.isNull(state)) {
			setState(getState(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setState(getState(defaultLocale), defaultLocale, defaultLocale);
		}

		String openingHours = getOpeningHours(defaultLocale);

		if (Validator.isNull(openingHours)) {
			setOpeningHours(
				getOpeningHours(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setOpeningHours(
				getOpeningHours(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public Dealer toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Dealer>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DealerImpl dealerImpl = new DealerImpl();

		dealerImpl.setUuid(getUuid());
		dealerImpl.setDealerId(getDealerId());
		dealerImpl.setGroupId(getGroupId());
		dealerImpl.setCompanyId(getCompanyId());
		dealerImpl.setUserId(getUserId());
		dealerImpl.setUserName(getUserName());
		dealerImpl.setCreateDate(getCreateDate());
		dealerImpl.setModifiedDate(getModifiedDate());
		dealerImpl.setName(getName());
		dealerImpl.setStreet(getStreet());
		dealerImpl.setLocality(getLocality());
		dealerImpl.setState(getState());
		dealerImpl.setPostalCode(getPostalCode());
		dealerImpl.setEmailAddress(getEmailAddress());
		dealerImpl.setPhoneNumber(getPhoneNumber());
		dealerImpl.setOpeningHours(getOpeningHours());
		dealerImpl.setLatitude(getLatitude());
		dealerImpl.setLongitude(getLongitude());
		dealerImpl.setDisplayDate(getDisplayDate());
		dealerImpl.setStatus(getStatus());
		dealerImpl.setStatusByUserId(getStatusByUserId());
		dealerImpl.setStatusByUserName(getStatusByUserName());
		dealerImpl.setStatusDate(getStatusDate());

		dealerImpl.resetOriginalValues();

		return dealerImpl;
	}

	@Override
	public Dealer cloneWithOriginalValues() {
		DealerImpl dealerImpl = new DealerImpl();

		dealerImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		dealerImpl.setDealerId(this.<Long>getColumnOriginalValue("dealerId"));
		dealerImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		dealerImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		dealerImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		dealerImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		dealerImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		dealerImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		dealerImpl.setName(this.<String>getColumnOriginalValue("name"));
		dealerImpl.setStreet(this.<String>getColumnOriginalValue("street"));
		dealerImpl.setLocality(this.<String>getColumnOriginalValue("locality"));
		dealerImpl.setState(this.<String>getColumnOriginalValue("state_"));
		dealerImpl.setPostalCode(
			this.<String>getColumnOriginalValue("postalCode"));
		dealerImpl.setEmailAddress(
			this.<String>getColumnOriginalValue("emailAddress"));
		dealerImpl.setPhoneNumber(
			this.<String>getColumnOriginalValue("phoneNumber"));
		dealerImpl.setOpeningHours(
			this.<String>getColumnOriginalValue("openingHours"));
		dealerImpl.setLatitude(
			this.<BigDecimal>getColumnOriginalValue("latitude"));
		dealerImpl.setLongitude(
			this.<BigDecimal>getColumnOriginalValue("longitude"));
		dealerImpl.setDisplayDate(
			this.<Date>getColumnOriginalValue("displayDate"));
		dealerImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		dealerImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		dealerImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		dealerImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return dealerImpl;
	}

	@Override
	public int compareTo(Dealer dealer) {
		int value = 0;

		value = getName().compareTo(dealer.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Dealer)) {
			return false;
		}

		Dealer dealer = (Dealer)object;

		long primaryKey = dealer.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Dealer> toCacheModel() {
		DealerCacheModel dealerCacheModel = new DealerCacheModel();

		dealerCacheModel.uuid = getUuid();

		String uuid = dealerCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			dealerCacheModel.uuid = null;
		}

		dealerCacheModel.dealerId = getDealerId();

		dealerCacheModel.groupId = getGroupId();

		dealerCacheModel.companyId = getCompanyId();

		dealerCacheModel.userId = getUserId();

		dealerCacheModel.userName = getUserName();

		String userName = dealerCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dealerCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dealerCacheModel.createDate = createDate.getTime();
		}
		else {
			dealerCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dealerCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dealerCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dealerCacheModel.name = getName();

		String name = dealerCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			dealerCacheModel.name = null;
		}

		dealerCacheModel.street = getStreet();

		String street = dealerCacheModel.street;

		if ((street != null) && (street.length() == 0)) {
			dealerCacheModel.street = null;
		}

		dealerCacheModel.locality = getLocality();

		String locality = dealerCacheModel.locality;

		if ((locality != null) && (locality.length() == 0)) {
			dealerCacheModel.locality = null;
		}

		dealerCacheModel.state = getState();

		String state = dealerCacheModel.state;

		if ((state != null) && (state.length() == 0)) {
			dealerCacheModel.state = null;
		}

		dealerCacheModel.postalCode = getPostalCode();

		String postalCode = dealerCacheModel.postalCode;

		if ((postalCode != null) && (postalCode.length() == 0)) {
			dealerCacheModel.postalCode = null;
		}

		dealerCacheModel.emailAddress = getEmailAddress();

		String emailAddress = dealerCacheModel.emailAddress;

		if ((emailAddress != null) && (emailAddress.length() == 0)) {
			dealerCacheModel.emailAddress = null;
		}

		dealerCacheModel.phoneNumber = getPhoneNumber();

		String phoneNumber = dealerCacheModel.phoneNumber;

		if ((phoneNumber != null) && (phoneNumber.length() == 0)) {
			dealerCacheModel.phoneNumber = null;
		}

		dealerCacheModel.openingHours = getOpeningHours();

		String openingHours = dealerCacheModel.openingHours;

		if ((openingHours != null) && (openingHours.length() == 0)) {
			dealerCacheModel.openingHours = null;
		}

		dealerCacheModel.latitude = getLatitude();

		dealerCacheModel.longitude = getLongitude();

		Date displayDate = getDisplayDate();

		if (displayDate != null) {
			dealerCacheModel.displayDate = displayDate.getTime();
		}
		else {
			dealerCacheModel.displayDate = Long.MIN_VALUE;
		}

		dealerCacheModel.status = getStatus();

		dealerCacheModel.statusByUserId = getStatusByUserId();

		dealerCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = dealerCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			dealerCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			dealerCacheModel.statusDate = statusDate.getTime();
		}
		else {
			dealerCacheModel.statusDate = Long.MIN_VALUE;
		}

		return dealerCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Dealer, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Dealer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Dealer, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Dealer)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Dealer, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Dealer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Dealer, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Dealer)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Dealer>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _dealerId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _nameCurrentLanguageId;
	private String _street;
	private String _streetCurrentLanguageId;
	private String _locality;
	private String _localityCurrentLanguageId;
	private String _state;
	private String _stateCurrentLanguageId;
	private String _postalCode;
	private String _emailAddress;
	private String _phoneNumber;
	private String _openingHours;
	private String _openingHoursCurrentLanguageId;
	private BigDecimal _latitude;
	private BigDecimal _longitude;
	private Date _displayDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Dealer, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Dealer)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("dealerId", _dealerId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("street", _street);
		_columnOriginalValues.put("locality", _locality);
		_columnOriginalValues.put("state_", _state);
		_columnOriginalValues.put("postalCode", _postalCode);
		_columnOriginalValues.put("emailAddress", _emailAddress);
		_columnOriginalValues.put("phoneNumber", _phoneNumber);
		_columnOriginalValues.put("openingHours", _openingHours);
		_columnOriginalValues.put("latitude", _latitude);
		_columnOriginalValues.put("longitude", _longitude);
		_columnOriginalValues.put("displayDate", _displayDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("state_", "state");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("dealerId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("street", 512L);

		columnBitmasks.put("locality", 1024L);

		columnBitmasks.put("state_", 2048L);

		columnBitmasks.put("postalCode", 4096L);

		columnBitmasks.put("emailAddress", 8192L);

		columnBitmasks.put("phoneNumber", 16384L);

		columnBitmasks.put("openingHours", 32768L);

		columnBitmasks.put("latitude", 65536L);

		columnBitmasks.put("longitude", 131072L);

		columnBitmasks.put("displayDate", 262144L);

		columnBitmasks.put("status", 524288L);

		columnBitmasks.put("statusByUserId", 1048576L);

		columnBitmasks.put("statusByUserName", 2097152L);

		columnBitmasks.put("statusDate", 4194304L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Dealer _escapedModel;

}